=== Install the SDK ===

Download SDK tools: http://www.sencha.com/products/sdk-tools/download/

<pre>chmod +x SenchaSDKTools-2.0.0-beta3-linux.run</pre>

<pre>sudo SenchaSDKTools-2.0.0-beta3-linux.run</pre>

Next, Next, Next :-(

=== Download ExtJs ===

Download ExtJs 4 from http://www.sencha.com/products/extjs/download
to .../geoext2/examples/app/simple/extjs-4.1.0

=== Build ===

 cd .../geoext2/examples/app/simple

Update the build:

 /opt/SenchaSDKTools-2.0.0-beta3/sencha create jsb -a simple-dev.html -p simple.jsb3

The simple.jsb3 is used as input and output, if it don't exists a new file will be created.

Build the application (withour OpenLayers):

 /opt/SenchaSDKTools-2.0.0-beta3/sencha build -d . -p simple.jsb3
